Ensure a run so caches are saved!

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -65,50 +65,50 @@ task:
     flutter config --no-analytics
     flutter update-packages
 
-  print_versions_script: |
-    dart --version
-    flutter --version
-    node --version
-    npm --version
+  # print_versions_script: |
+  #   dart --version
+  #   flutter --version
+  #   node --version
+  #   npm --version
 
-  flutter_doctor_script: |
-    flutter doctor
+  # flutter_doctor_script: |
+  #   flutter doctor
 
-  install_npm_packages_script: |
-    npm install --depth 0 --unsafe-perm
+  # install_npm_packages_script: |
+  #   npm install --depth 0 --unsafe-perm
 
-  configure_code_climate_script: |
-    if [[ "$OS" == "linux" ]; then
-      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
-    else
-      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter;
-    fi
-    chmod +x ./cc-test-reporter;
-    ./cc-test-reporter before-build;
+  # configure_code_climate_script: |
+  #   if [[ "$OS" == "linux" ]; then
+  #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
+  #   else
+  #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter;
+  #   fi
+  #   chmod +x ./cc-test-reporter;
+  #   ./cc-test-reporter before-build;
 
-  compile_script: |
-    npm run vscode:prepublish
+  # compile_script: |
+  #   npm run vscode:prepublish
 
-  lint_script: |
-    npm run lint
+  # lint_script: |
+  #   npm run lint
 
-  test_script: |
-    npm test
+  # test_script: |
+  #   npm test
 
-  ensure_no_dart_processes_script: |
-    ps -ax | grep -v grep | grep dart || true
-    if [[ $(pgrep -x dart) ]]; then
-      echo 'DART WAS FOUND';
-      fail();
-    fi;
+  # ensure_no_dart_processes_script: |
+  #   ps -ax | grep -v grep | grep dart || true
+  #   if [[ $(pgrep -x dart) ]]; then
+  #     echo 'DART WAS FOUND';
+  #     fail();
+  #   fi;
 
-  upload_logs_script: |
-    if [[ "$CIRRUS_PR" = "" ]; then
-      dpl --provider=s3 --bucket="test-results.dartcode.org" --skip_cleanup=true --local-dir=".test_results" --upload-dir="$CIRRUS_BRANCH/$CIRRUS_CHANGE_IN_REPO/Cirrus-$OS" --acl=public_read --default_text_charset=utf-8;
-      dpl --provider=s3 --bucket="test-results.dartcode.org" --skip_cleanup=true --local-dir=".dart_code_test_logs" --upload-dir="logs/$CIRRUS_BRANCH/$CIRRUS_CHANGE_IN_REPO/Cirrus-$OS" --acl=public_read --default_text_charset=utf-8;
-    fi
+  # upload_logs_script: |
+  #   if [[ "$CIRRUS_PR" = "" ]; then
+  #     dpl --provider=s3 --bucket="test-results.dartcode.org" --skip_cleanup=true --local-dir=".test_results" --upload-dir="$CIRRUS_BRANCH/$CIRRUS_CHANGE_IN_REPO/Cirrus-$OS" --acl=public_read --default_text_charset=utf-8;
+  #     dpl --provider=s3 --bucket="test-results.dartcode.org" --skip_cleanup=true --local-dir=".dart_code_test_logs" --upload-dir="logs/$CIRRUS_BRANCH/$CIRRUS_CHANGE_IN_REPO/Cirrus-$OS" --acl=public_read --default_text_charset=utf-8;
+  #   fi
 
-  upload_code_coverage_script: |
-    if [[ "$CODE_VERSION" == "stable" ]] && [[ "$DART_CHANNEL" == "stable" ]]; then
-      ./cc-test-reporter after-build --prefix ../../;
-    fi
+  # upload_code_coverage_script: |
+  #   if [[ "$CODE_VERSION" == "stable" ]] && [[ "$DART_CHANNEL" == "stable" ]]; then
+  #     ./cc-test-reporter after-build --prefix ../../;
+  #   fi
